### ISSUE TITLE
Fix metadata specification for all modules

### ISSUE THREAD

**Issue by AlexVCaron** [scilus/nf-neuro#104]
Metadata specified in `meta.yml` related and outputs is possibly badly formatted. In most module, we still have something of the sort :

```yaml
outputs:
    meta: ...
    image_blabla: ...
    data_blabla: ...
```

But that is not how outputs are formed, they are all individual (mostly), in a tuple prefixed with the `meta` map. Instead, we should format outputs like we do for subworkflows, using the `Structure` keyword in the description :

```yaml
outputs:
    image_blabla:
        type: ...
        description: |
            This is my blabla image. It is blabla. Structure : [ val(meta), path(image_blabla) ]
```
